server:
  port: 8081
  servlet:
    context-path: /api
    session:
      cookie:
        domain: user.kongshier.top
        same-site: lax
        secure: false
spring:
  application:
    name: shier-user-center
  datasource:
    url: jdbc:mysql://xxxxx/user-center?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: shier
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  config:
    activate:
      on-profile: -prod
  # session登录态超时时间
  session:
    timeout: 86400
# 自动转换为驼峰
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
aliyun:
  oss:
    file:
      endpoint: xxxx
      keyid: xxx
      keysecret: xx
      bucketname: xxxxxx
